### ISSUE TITLE
Amending the regex code 

### ISSUE THREAD

**Issue by 2001asjad** [2001asjad/ReGexRepo#5]
Currently this regex code ```(?:http|ftp|https):\/\/ci\.adoptopenjdk\.net.+\/(?=console)|(?<=\`).+?\/(?=\`)``` works just fine.
In order to make it more convenient can't we break it into 2 patterns, one for the `https://` part and the other for the backticks part, in the regexify function? Like adding a conditional?
because I want to make internal build `Test_openjdk8_j9_sanity.openjdk_aarch64_linux/43/` into this: `https://internal_jenkins/job/Test_openjdk8_j9_sanity.openjdk_aarch64_linux/43/`, like I want to add `https://internal_jenkins/job/` in the beginning of the links that are in backticks.
is there are any way @AmaaniGoose?

**Comment by AmaaniGoose** [comment]
?:(?:http|ftp|https):\/\/ci\.adoptopenjdk\.net.+\/(?=console))|(?:Test_openjdk\d.+\/

This should work for testing for both

For appending internal Jenkins we need some manipulation in the python code

**Comment by AmaaniGoose** [comment]
(?:http|ftp|https)://ci.adoptopenjdk.net.+/(?=console)

Test_openjdk\d.+/

These are the two patterns
